language: java
jdk:
  - openjdk11

branches:
  only:
    - master


# travis Ci 서버의 home
cache:
directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x ./gradlew
before_deploy:
  - zip -r springboot-aws-webservice *
  - mkdir -p deploy
  - mv springboot-aws-webservice.zip deploy/springboot-aws-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: springboot-aws-webservice-s3
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: springboot-aws-webservice-s3
    key: springboot-aws-webservice.zip

    bundle_type: zip
    application: springboot-aws-webservice
    
    deployment_group: springboot-aws-webservice-group
    
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - wkb1848@gmail.com


      # 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

