spring:
    jpa: 
        hibernate:
            ddl-auto: none

        show-sql: false

    datasource:
        hikari:
            jdbc-url: jdbc:mariadb://springboot-aws-webservice.cdlwsp88xypb.ap-northeast-2.rds.amazonaws.com:3306/springboot-aws
            username: orangeblue
            password: killyou11!

            driver-class-name: org.mariadb.jdbc.Driver

            