spring:
  security:
    oauth2:
      client:
        registration:

          google:
            client-id: 56197222956-u8kriu0ju68ju0i19ajuj8f7e6ejlkou.apps.googleusercontent.com
            client-secret: 6VUFnWYoZ4tQ6ULHkWgAg1_b
            scope:
            - profile
            - email

          naver:
            client-id: Zst1nfK5XzDo_OIOakOT
            client-secret: tD8ZvXhiTm
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          