spring:
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true

    profiles:
        include:
        - oauth 

    datasource:
        url: jdbc:h2:mem:testdb 
    
    thymeleaf:
        prefix: classpath:templates/
        suffix: .html 

    h2:
        console:
            enabled: true

    session:
        store-type: jdbc

                    



        


